### PR TITLE
print the name of typeclass on which test failed

### LINKED ISSUE #39: Report the type class names on which the test failed
I am using something like this:

```
inspect $ hasNoTypeClassesExcept 'fromStreamVar [''Exception]
```

The test fails and dumps the core output. However, the core output is long and it is hard figure out which typeclass it failed on. Is it possible to print the name of the type class on which it failed?

### PR DESCRIPTION
**Pull request by harendra-kumar**
Fixes #39

### CODE REVIEW

File: src/Test/Inspection/Core.hs [hunk 1]
```diff
@@ -203,43 +205,56 @@ eqSlice it slice1 slice2
...
 freeOfType :: Slice -> [Name] -> Maybe (Var, CoreExpr)
-freeOfType slice tcNs = allTyCons (\tc -> getName tc `notElem` tcNs) slice
-
-allTyCons :: (TyCon -> Bool) -> Slice -> Maybe (Var, CoreExpr)
-allTyCons predicate slice = listToMaybe [ (v,e) | (v,e) <- slice, not (go e) ]
+freeOfType slice tcNs =
+      fmap (\(a,b,_) -> (a,b))
+    $ allTyCons (\tc -> getName tc `notElem` tcNs) slice
+
+allTyCons :: (TyCon -> Bool) -> Slice -> Maybe (Var, CoreExpr, TyCon)
```
Comment (nomeata) [inline src/Test/Inspection/Core.hs]: Might you add a comment about what the function does?

File: src/Test/Inspection/Core.hs [hunk 2]
```diff
@@ -203,43 +205,56 @@ eqSlice it slice1 slice2
...
+allTyCons predicate slice =
+    listToMaybe $ do
+        (v,e) <- slice
+        case runExcept (go e) of
+            Right _ -> A.empty
+            Left tc -> return (v,e,tc)
```
Comment (nomeata) [inline src/Test/Inspection/Core.hs]: Does this warrant a monad and the slightly complicated control flow of the `Except` monad?

It seems you could change the return type of `go` from `Bool` to `[TyCon]`, simply replacing `&&` with `++`; `True` with `[]`, `all` with `concatMap`

File: src/Test/Inspection/Core.hs (hunk 1 above)
Comment (harendra-kumar) [reply src/Test/Inspection/Core.hs]: Will do.

File: src/Test/Inspection/Core.hs (hunk 2 above)
Comment (harendra-kumar) [reply src/Test/Inspection/Core.hs]: Yes, that should work.

File: src/Test/Inspection/Core.hs [hunk 3]
```diff
@@ -203,43 +204,49 @@ eqSlice it slice1 slice2
...
+freeOfType slice tcNs =
+      fmap (\(a,b,_) -> (a,b))
+    $ allTyCons (\tc -> getName tc `notElem` tcNs) slice
+
+-- | Check if all type constructors in a slice satisfy the given predicate.
+-- Returns the binder, expression and failing constructors triple on failure.
+allTyCons :: (TyCon -> Bool) -> Slice -> Maybe (Var, CoreExpr, [TyCon])
+allTyCons predicate slice =
+    listToMaybe
+        [(v, e, nub tcs) | (v, e) <- slice, let tcs = go e, not (null tcs)]
```
Comment (nomeata) [inline src/Test/Inspection/Core.hs]: A `Slice` is a list of binders, so it is a bit odd to return just _one_ binder, but _all_ tycons therein: Either report the first error (one binder, one tc), or all binders and all tcs. I think the former should suffice. Would also avoid the (O(n)!) `nub. Something like the simple and elegant
```suggestion
        [(v, e, tc) | (v, e) <- slice, tc <- go e]
```
(with just `TyCon`, not `[TyCon]` in the type for `allTycons`).

Comment (harendra-kumar) [reply src/Test/Inspection/Core.hs]: I thought it may be helpful in practice to report all the tycons because we can report that without using a lot of real estate in the output, I know we are not doing that for binders but it does not cause any harm other than annoying the perfectionist mind. I am neutral on this change. You can change it before merging.

File: src/Test/Inspection/Core.hs [hunk 4]
```diff
@@ -203,43 +204,49 @@ eqSlice it slice1 slice2
...
-    goA (_,pats, e) = all goV pats && go e
+    goA (_,pats, e) = concatMap goV pats >> go e
 
-    goT (TyVarTy _)      = True
-    goT (AppTy t1 t2)    = goT t1 && goT t2
-    goT (TyConApp tc ts) = predicate tc && all goT ts
-                        -- ↑ This is the crucial bit
+    goT (TyVarTy _)      = []
+    goT (AppTy t1 t2)    = goT t1 ++ goT t2
+    goT (TyConApp tc ts) = if predicate tc then concatMap goT ts else [tc]
```
[the remark this answers is not in the document]
Comment (harendra-kumar) [reply src/Test/Inspection/Core.hs]: I find the first one faster to understand but I know it is subjective.

[the remark this answers is not in the document]
Comment (nomeata) [reply src/Test/Inspection/Core.hs]: It’s not only simpler, but “more correct”: Since you want to print all ty-cons (see discussion below), if one of those appears as an argument to another one, your code will prevent that, as it doesn't traverse `ts` in all cases.

[the remark this answers is not in the document]
Comment (harendra-kumar) [reply src/Test/Inspection/Core.hs]: yes, you are right about that, I overlooked this aspect. In that case list comprehension version is shorter, and better if one is used to it.

**Comment by nomeata** [comment]
Just click “commit suggestion” for the list comprehension, then I’ll merge.

**Comment by harendra-kumar** [comment]
Somehow I cannot find any "commit suggestion" option or any checkbox around the suggestion. I can't find anything at all that I can do with the suggestion other than viewing it.

**Comment by nomeata** [comment]
Odd. I’ll do it manually.

File: src/Test/Inspection/Core.hs [hunk 5]
```diff
@@ -203,43 +204,49 @@ eqSlice it slice1 slice2
...
     go (Tick _ e)        = go e
     go (Type t)          = (goT t)
-    go (Coercion _)      = True
+    go (Coercion _)      = []
 
-    goB (b, e) = goV b && go e
+    goB (b, e) = goV b ++ go e
 
-    goA (_,pats, e) = all goV pats && go e
+    goA (_,pats, e) = concatMap goV pats >> go e
```
Comment (rjmk) [inline src/Test/Inspection/Core.hs]: I'm surprised to see `>>` here. Is it supposed to be `>>=`?

Comment (harendra-kumar) [reply src/Test/Inspection/Core.hs]: Thanks for catching the bug! This should have been `++` instead of `>>`.  This should be the cause of #41 .

In the older version of the PR we were using `ExceptT` and `>>` was the right thing then. When it was changed to use `concatMap` `>>` was changed to `++`, this particular instance remained somehow.

Comment (nomeata) [reply src/Test/Inspection/Core.hs]: Well spotted! :-)
