### PR TITLE
Ignores HPC ticks in `(==-)`

### LINKED ISSUE #47: `(==-)` should ignore coverage-related core functions
When built with `-fhpc` ghc flag or `--coverage` stack option, core representation can be different than those without coverage options.

Consider the following:

```haskell
{-# OPTIONS_GHC -fhpc -O2 #-}
{-# LANGUAGE TemplateHaskell #-}
module Main where
import Test.Inspection

theTwo :: Int
theTwo = 2

theOnePlusOne :: Int
theOnePlusOne = 1 + 1

anotherTwo :: Int
anotherTwo = 2

inspect $ 'theTwo ==- 'theOnePlusOne
inspect $ 'theTwo ==- 'anotherTwo

main :: IO ()
main = print theOnePlusOne
```

Without `-fhpc` option, this compiles successfully; but with `-fhpc` option, we will get the following compilation error:

```
[1 of 1] Compiling Main
/Users/hiromi/Documents/Programming/Haskell/git/coverage-and-inspection/src/Main.hs:15:1: theTwo ==- theOnePlusOne failed:
    LHS:
        theTwo :: Int
        [LclIdX,
         Unf=Unf{Src=<vanilla>, TopLvl=True, Value=False, ConLike=False,
                 WorkFree=False, Expandable=False, Guidance=IF_ARGS [] 10 20}]
        theTwo = hpc<Main,10> hpc<Main,9> I# 2#
        
    RHS:
        theOnePlusOne :: Int
        [LclIdX,
         Unf=Unf{Src=<vanilla>, TopLvl=True, Value=False, ConLike=False,
                 WorkFree=False, Expandable=False, Guidance=IF_ARGS [] 10 20}]
        theOnePlusOne
          = hpc<Main,8> hpc<Main,7> hpc<Main,5> hpc<Main,6> I# 2#
        
/Users/hiromi/Documents/Programming/Haskell/git/coverage-and-inspection/src/Main.hs:16:1: theTwo ==- anotherTwo failed:
    LHS:
        theTwo :: Int
        [LclIdX,
         Unf=Unf{Src=<vanilla>, TopLvl=True, Value=False, ConLike=False,
                 WorkFree=False, Expandable=False, Guidance=IF_ARGS [] 10 20}]
        theTwo = hpc<Main,10> hpc<Main,9> I# 2#
        
    RHS:
        anotherTwo :: Int
        [LclIdX,
         Unf=Unf{Src=<vanilla>, TopLvl=True, Value=False, ConLike=False,
                 WorkFree=False, Expandable=False, Guidance=IF_ARGS [] 10 20}]
        anotherTwo = hpc<Main,4> hpc<Main,3> I# 2#
        

src/Main.hs: error:
    inspection testing unsuccessful
         unexpected failures: 2
```

If all the tested functionalities are provided in the single module and no other tests are taken place, just adding `-fno-hpc` GHC option would suffice.
But, in general, there can be non-inspection tests for the same functionalities, or worse, the functions are scattered across multiple libraries.
In such a situation, if one wants to get the coverage report for them, one has to compile the library with `-fhpc` flag.
Then, the closures of form `hpc` still remain in the Core.
This means that one has to build libraries twice (once with `-fhpc` and then `-fno-hpc`) and separate test programs to control the timing of inspection tests.

It might be good to ignore `hpc` in `(==-)`, as coercions and type lambdas are already ignored.

### PR DESCRIPTION
**Pull request by konn**
`-fhpc` flag generates extra `HPCTick` Tickish in the Core, which prevents using `inspection-testing` with Haskell Program Coverage tool.
This pull-request gently ignores `Tick HPCTick{}` when the "ignore" option in `mkEquality` is enabled.

This closes #47.

### CODE REVIEW

**Comment by konn** [comment]
Oh, it seems that I forgot to turn off the code-formatter. I will revert some changes shortly.

**Comment by konn** [comment]
I've just (force-)pushed the commit containing relevant changes. Sorry for the inconvenience.

**Comment by konn** [comment]
It seems that some (dependently-typed) usages of `(==-)` is still failing in my personal project.
The above correction of `essentiallyVar` is intended to cover such cases, but I'm not confident that it fixes the issue.
I will create a minimal repro and check if the above commit covers such cases.

**Comment by konn** [comment]
OK, here is a minimal case:

```haskell
data SBool (p :: Bool) where
  STrue  :: SBool 'True
  SFalse :: SBool 'False

class KnownBool (p :: Bool) where
  sing :: SBool p

instance KnownBool 'True where
  sing = STrue

instance KnownBool 'False where
  sing = SFalse

conditionallyTwo
  :: KnownBool (n <=? 3) => Proxy n -> Int
{-# INLINE conditionallyTwo #-}
conditionallyTwo (Proxy :: Proxy n) =
  case sing :: SBool (n <=? 3) of
    STrue  -> 2
    SFalse -> 42

yetAnotherTwo :: Int
yetAnotherTwo = conditionallyTwo (Proxy :: Proxy 2)

inspect $ 'theTwo ==- 'yetAnotherTwo
```

I'm now convinced that we cannot cover this case immediately in `inspection-testing`.
HPC must keep track of the branch of case-expressions and such requirement definitely prevents some sort of optimisation.
In the above code, if `-fhpc` is off then `yetAnotherTwo` is almost equal to `2`.
On the other hand, with `-fhpc`, two branches remains in the Core to keep track of coverage of data flow, hence results in the Core with case-splitting remaining.

Still, I think it is worthy to ignore the HPC ticks in `(==-)`. However, since this feature is not complete, it could make sense to add a comment concerning optimisation vs HPC pitfalls.

I will remove draft state after I add such notes in the Haddock.

File: src/Test/Inspection.hs [hunk 1]
```diff
@@ -112,7 +112,9 @@ data Property
     -- In general @f@ and @g@ need to be defined in this module, so that their
     -- actual defintions can be inspected.
     --
-    -- If the boolean flag is true, then ignore types during the comparison.
+    -- If the boolean flag is true, then ignore types and hpc ticks
+    -- during the comparison.
+    -- See the note of '==-' for the pitfalls with coverage test.
```
Comment (nomeata) [inline src/Test/Inspection.hs:117]:
```suggestion
    -- If the boolean flag is true, then ignore types and hpc ticks
    -- during the comparison.
```

File: src/Test/Inspection.hs [hunk 2]
```diff
@@ -155,7 +157,12 @@ These convenience functions create common test obligations directly.
 infix 9 ===
 
 -- | Declare two functions to be equal, but ignoring
--- type lambdas, type arguments and type casts (see 'EqualTo')
+-- hpc ticks, type lambdas, type arguments and type casts (see 'EqualTo').
+--
+-- Note: If the code being inspected contains if- or case-expression,
+-- the generated Core can contain trivial branching, even with @-O2@ option.
+-- To test the optimised code correctly, we recommend turning off @-fhpc@ option,
+-- and testing against libraries compiled /without/ @-fhpc@ (or equivalent) option.
```
Comment (nomeata) [inline src/Test/Inspection.hs:165]: Thanks! I’d like to make the “hpc tick” comment less prominent; I don’t want to scare people that don't know what these are away from the library :-)

```suggestion
-- type lambdas, type arguments, type casts and hpc ticks (see 'EqualTo').
-- Note that `-fhpc` can prevent some optimizations; build without for more reliable analysis.
```
